### ISSUE TITLE
Rename to Repo Automator?

### ISSUE THREAD

**Issue by jeffpaul** [10up/action-pr-helper#73]
### Describe your question

Given the scope of this action has expanded beyond just PR automations to other items covering issue automations and project/repo management, it might make sense to update the name (again) to Repo Automator?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
I'm fine with a rename but any concerns with repos that are using this action? I'm assuming they'd all need to be updated for things to still work, though I guess not sure how best to handle deprecations/renames with GitHub Actions. Looking at the last PR that renamed things (#27) not seeing any discussion there around that concern so maybe it's not a big deal?

**Comment by iamdharmesh** [comment]
@jeffpaul I think we are good to proceed with Rename.

> I guess not sure how best to handle deprecations/renames with GitHub Actions. Looking at the last PR that renamed things (https://github.com/10up/action-pr-automator/pull/27) not seeing any discussion there around that concern so maybe it's not a big deal?

We don't have many users using this action, only internal 10up repos using this action. So, we can easily update the workflows to accommodate this rename.

Thanks

**Comment by jeffpaul** [comment]
@iamdharmesh I can handle the repo rename, but are there any code-related updates to make as well (e.g. action.yml) in a PR that can get merged once the repo's renamed?

**Comment by iamdharmesh** [comment]
@jeffpaul we have to do code level updates at multiple [places](https://github.com/search?q=repo%3A10up%2Faction-pr-automator+pr+automator&type=code). I will raise PR and will ask you to rename the repo.

Also, once rename is handled here, I will raise the PRs for the repos where we are using this action.

Thanks
